version: "3"
services:
  php:
    build: docker/php-fpm
    environment:
      - XDEBUG_CONFIG=remote_host=${LOCAL_IP} idekey=PHPSTORM
      - http_proxy
      - https_proxy
      - no_proxy
    volumes:
      - ./:/var/www/superproject
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./var/log:/var/log

  nginx:
    image: nginx:latest
    links:
      - php
    ports:
      - 8880:80
    volumes:
      - ./:/var/www/superproject
      - ./docker/nginx/nginx_local.conf:/etc/nginx/conf.d/default.conf
      - ./container-data/nginx_logs/:/var/log/nginx/
      - ./var/log:/var/log

  postgres:
      image: postgres:9.6
      environment:
        - POSTGRES_USER=dev
        - POSTGRES_PASSWORD=dev
        - POSTGRES_DB=superproject
      volumes:
        - ./container-data/postgrees:/var/lib/postgresql/data
      ports:
        - ${POSTGRES_PORT}:5432
