parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: '%services_defaults_public%'

#####   RESOURCES

    App\Port\Controller\:
        resource: ../src/Port/Controller/
        tags: ['controller.service_arguments']

    App\Domain\:
        resource: ../src/Domain/*/{Service,Repository,EventSubscriber}

